### ISSUE TITLE
unknown errors: too many open files

### ISSUE THREAD

**Issue by ziqilau** [GraphChi/graphchi-cpp#39]
I just input the matrix market format data of netflix, then get the following error:

ERROR:    stripedio.hpp(open_session:404): Could not open: graphchi_train.edata..Z.e4B.4_5_blockdir_1048576/60 session: 1023 error: Too many open files
biassgd: ../../src/io/stripedio.hpp:406: int graphchi::stripedio::open_session(std::string, bool, bool): Assertion `rddesc>=0' failed.

------------------------details------------------------
./toolkits/collaborative_filtering/biassgd --training=graphchi_train --validation=graphchi_test --biassgd_lambda=1e-4 --biassgd_gamma=1e-4 --minval=1 --maxval=5 --max_iter=10
WARNING:  common.hpp(print_copyright:214): GraphChi Collaborative filtering library is written by Danny Bickson (c). Send any  comments or bug reports to danny.bickson@gmail.com 
[training] => [graphchi_train]
[validation] => [graphchi_test]
[biassgd_lambda] => [1e-4]
[biassgd_gamma] => [1e-4]
[minval] => [1]
[maxval] => [5]
[max_iter] => [10]
INFO:     chifilenames.hpp(find_shards:265): Detected number of shards: 5
INFO:     chifilenames.hpp(find_shards:266): To specify a different number of shards, use command-line parameter 'nshards'
INFO:     io.hpp(convert_matrixmarket:509): File graphchi_train was already preprocessed, won't do it again. 
INFO:     io.hpp(read_global_mean:109): Opened matrix size: 480189 x 17770 edges: 99072112 Global mean is: 3.6033 time bins: 0 Now creating shards.
INFO:     chifilenames.hpp(find_shards:265): Detected number of shards: 1
INFO:     chifilenames.hpp(find_shards:266): To specify a different number of shards, use command-line parameter 'nshards'
INFO:     io.hpp(convert_matrixmarket:509): File graphchi_test was already preprocessed, won't do it again. 
INFO:     io.hpp(read_global_mean:111): Opened VLIDATION matrix size: 480189 x 17770 edges: 1408395 Global mean is: 3.67363 time bins: 0 Now creating shards.
DEBUG:    stripedio.hpp(stripedio:271): Start io-manager with 2 threads.
INFO:     graphchi_engine.hpp(graphchi_engine:154): Initializing graphchi_engine. This engine expects 4-byte edge data. 
INFO:     chifilenames.hpp(load_vertex_intervals:400): shard: 0 - 497958
DEBUG:    stripedio.hpp(stripedio:271): Start io-manager with 2 threads.
INFO:     graphchi_engine.hpp(graphchi_engine:154): Initializing graphchi_engine. This engine expects 4-byte edge data. 
INFO:     chifilenames.hpp(load_vertex_intervals:400): shard: 0 - 484050
INFO:     chifilenames.hpp(load_vertex_intervals:400): shard: 484051 - 487367
INFO:     chifilenames.hpp(load_vertex_intervals:400): shard: 487368 - 491268
INFO:     chifilenames.hpp(load_vertex_intervals:400): shard: 491269 - 494699
INFO:     chifilenames.hpp(load_vertex_intervals:400): shard: 494700 - 497958
INFO:     graphchi_engine.hpp(run:744): GraphChi starting
INFO:     graphchi_engine.hpp(run:745): Licensed under the Apache License 2.0
INFO:     graphchi_engine.hpp(run:746): Copyright Aapo Kyrola et al., Carnegie Mellon University (2012)
DEBUG:    slidingshard.hpp(sliding_shard:213): Total edge data size: 79274092, graphchi_train.edata..Z.e4B.0_5sizeof(ET): 4
DEBUG:    slidingshard.hpp(sliding_shard:213): Total edge data size: 79256548, graphchi_train.edata..Z.e4B.1_5sizeof(ET): 4
DEBUG:    slidingshard.hpp(sliding_shard:213): Total edge data size: 79273696, graphchi_train.edata..Z.e4B.2_5sizeof(ET): 4
DEBUG:    slidingshard.hpp(sliding_shard:213): Total edge data size: 79245960, graphchi_train.edata..Z.e4B.3_5sizeof(ET): 4
DEBUG:    slidingshard.hpp(sliding_shard:213): Total edge data size: 79238152, graphchi_train.edata..Z.e4B.4_5sizeof(ET): 4
INFO:     graphchi_engine.hpp(print_config:132): Engine configuration: 
INFO:     graphchi_engine.hpp(print_config:133):  exec_threads = 8
INFO:     graphchi_engine.hpp(print_config:134):  load_threads = 4
INFO:     graphchi_engine.hpp(print_config:135):  membudget_mb = 800
INFO:     graphchi_engine.hpp(print_config:136):  blocksize = 1048576
INFO:     graphchi_engine.hpp(print_config:137):  scheduler = 0
INFO:     graphchi_engine.hpp(run:780): Start iteration: 0
DEBUG:    rmse_engine.hpp(reset_rmse:148): Detected number of threads: 8
INFO:     graphchi_engine.hpp(run:859): 0.000446s: Starting: 0 -- 484050
DEBUG:    graphchi_engine.hpp(determine_next_window:325): Memory budget exceeded with 838868704 bytes.
INFO:     graphchi_engine.hpp(run:872): Iteration 0/9, subinterval: 0 - 80199
DEBUG:    graphchi_engine.hpp(run:887): Allocation 80200 vertices, sizeof:64 total:5132800
DEBUG:    memoryshard.hpp(load_edata:327): Compressed/full size: 0.172229 number of blocks: 76
INFO:     graphchi_engine.hpp(run:896): Start updates
INFO:     graphchi_engine.hpp(run:906): Finished updates
DEBUG:    graphchi_engine.hpp(determine_next_window:325): Memory budget exceeded with 838865568 bytes.
INFO:     graphchi_engine.hpp(run:872): Iteration 0/9, subinterval: 80200 - 234145
DEBUG:    graphchi_engine.hpp(run:887): Allocation 153946 vertices, sizeof:64 total:9852544
INFO:     graphchi_engine.hpp(run:896): Start updates
INFO:     graphchi_engine.hpp(run:906): Finished updates
INFO:     graphchi_engine.hpp(run:872): Iteration 0/9, subinterval: 234146 - 484050
DEBUG:    graphchi_engine.hpp(run:887): Allocation 249905 vertices, sizeof:64 total:15993920
INFO:     graphchi_engine.hpp(run:896): Start updates
INFO:     graphchi_engine.hpp(run:906): Finished updates
INFO:     graphchi_engine.hpp(run:859): 3.83968s: Starting: 484051 -- 487367
INFO:     graphchi_engine.hpp(run:872): Iteration 0/9, subinterval: 484051 - 487367
DEBUG:    graphchi_engine.hpp(run:887): Allocation 3317 vertices, sizeof:64 total:212288
DEBUG:    memoryshard.hpp(load_edata:327): Compressed/full size: 0.172574 number of blocks: 76
INFO:     graphchi_engine.hpp(run:896): Start updates
INFO:     graphchi_engine.hpp(run:906): Finished updates
INFO:     graphchi_engine.hpp(run:859): 4.27056s: Starting: 487368 -- 491268
INFO:     graphchi_engine.hpp(run:872): Iteration 0/9, subinterval: 487368 - 491268
DEBUG:    graphchi_engine.hpp(run:887): Allocation 3901 vertices, sizeof:64 total:249664
DEBUG:    memoryshard.hpp(load_edata:327): Compressed/full size: 0.172775 number of blocks: 76
INFO:     graphchi_engine.hpp(run:896): Start updates
INFO:     graphchi_engine.hpp(run:906): Finished updates
INFO:     graphchi_engine.hpp(run:859): 4.57392s: Starting: 491269 -- 494699
INFO:     graphchi_engine.hpp(run:872): Iteration 0/9, subinterval: 491269 - 494699
DEBUG:    graphchi_engine.hpp(run:887): Allocation 3431 vertices, sizeof:64 total:219584
DEBUG:    memoryshard.hpp(load_edata:327): Compressed/full size: 0.171853 number of blocks: 76
INFO:     graphchi_engine.hpp(run:896): Start updates
INFO:     graphchi_engine.hpp(run:906): Finished updates
INFO:     graphchi_engine.hpp(run:859): 4.86931s: Starting: 494700 -- 497958
INFO:     graphchi_engine.hpp(run:872): Iteration 0/9, subinterval: 494700 - 497958
DEBUG:    graphchi_engine.hpp(run:887): Allocation 3259 vertices, sizeof:64 total:208576
DEBUG:    memoryshard.hpp(load_edata:327): Compressed/full size: 0.172008 number of blocks: 76
INFO:     graphchi_engine.hpp(run:896): Start updates
INFO:     graphchi_engine.hpp(run:906): Finished updates
   5.38353) Iteration:   0 Training RMSE:   1.32668INFO:     graphchi_engine.hpp(run:744): GraphChi starting
INFO:     graphchi_engine.hpp(run:745): Licensed under the Apache License 2.0
INFO:     graphchi_engine.hpp(run:746): Copyright Aapo Kyrola et al., Carnegie Mellon University (2012)
DEBUG:    slidingshard.hpp(sliding_shard:213): Total edge data size: 5633580, graphchi_test.edata..Z.e4B.0_1sizeof(ET): 4
INFO:     graphchi_engine.hpp(print_config:132): Engine configuration: 
INFO:     graphchi_engine.hpp(print_config:133):  exec_threads = 8
INFO:     graphchi_engine.hpp(print_config:134):  load_threads = 4
INFO:     graphchi_engine.hpp(print_config:135):  membudget_mb = 800
INFO:     graphchi_engine.hpp(print_config:136):  blocksize = 1048576
INFO:     graphchi_engine.hpp(print_config:137):  scheduler = 0
INFO:     graphchi_engine.hpp(run:780): Start iteration: 0
INFO:     graphchi_engine.hpp(run:859): 5.1685s: Starting: 0 -- 497958
INFO:     graphchi_engine.hpp(run:872): Iteration 0/0, subinterval: 0 - 497958
DEBUG:    graphchi_engine.hpp(run:887): Allocation 497959 vertices, sizeof:64 total:31869376
DEBUG:    memoryshard.hpp(load_edata:327): Compressed/full size: 0.180397 number of blocks: 6
INFO:     graphchi_engine.hpp(run:896): Start updates
INFO:     graphchi_engine.hpp(exec_updates_inmemory_mode:470): In-memory mode: Iteration 0 starts. (5.23427 secs)
  Validation  RMSE:   1.23962
INFO:     graphchi_engine.hpp(run:906): Finished updates
INFO:     graphchi_engine.hpp(run:780): Start iteration: 1
DEBUG:    rmse_engine.hpp(reset_rmse:148): Detected number of threads: 8
INFO:     graphchi_engine.hpp(run:859): 5.27579s: Starting: 0 -- 484050
DEBUG:    graphchi_engine.hpp(determine_next_window:325): Memory budget exceeded with 838868704 bytes.
INFO:     graphchi_engine.hpp(run:872): Iteration 1/9, subinterval: 0 - 80199
DEBUG:    graphchi_engine.hpp(run:887): Allocation 80200 vertices, sizeof:64 total:5132800
DEBUG:    memoryshard.hpp(load_edata:327): Compressed/full size: 0.172229 number of blocks: 76
INFO:     graphchi_engine.hpp(run:896): Start updates
INFO:     graphchi_engine.hpp(run:906): Finished updates
DEBUG:    graphchi_engine.hpp(determine_next_window:325): Memory budget exceeded with 838865568 bytes.
INFO:     graphchi_engine.hpp(run:872): Iteration 1/9, subinterval: 80200 - 234145
DEBUG:    graphchi_engine.hpp(run:887): Allocation 153946 vertices, sizeof:64 total:9852544

ERROR:    stripedio.hpp(open_session:404): Could not open: graphchi_train.edata..Z.e4B.4_5_blockdir_1048576/60 session: 1023 error: Too many open files
biassgd: ../../src/io/stripedio.hpp:406: int graphchi::stripedio::open_session(std::string, bool, bool): Assertion `rddesc>=0' failed.

**Comment by ziqilau** [comment]
my input is like so:
%%MatrixMarket matrix coordinate real general
480189 17770 99072112
245203 12140 3
16324 11630 1
47729 10170 5
413766 3936 5
306696 6042 3
31073 10851 3

**Comment by akyrola** [comment]
Too many open files means that you do not have enough file descriptors
configured. See
https://github.com/GraphChi/graphchi-cpp/wiki/Troubleshooting
