### ISSUE TITLE
SVD computation fails

### ISSUE THREAD

**Issue by Prokopp** [GraphChi/graphchi-cpp#8]
Hi,

I tried to SVD a 14.6m*14.6m matrix with ~213m values on a 32 core machine with 244GB RAM. It failed thrice. Any hints are welcome.

Here are the three commands and error messages:

$ toolkits/collaborative_filtering/svd --training=/mnt/2/data.mm.mtx --nsv=50 --nv=55

INFO:     graphchi_engine.hpp(run:838): 146.755s: Starting: 400798 -- 626074
INFO:     graphchi_engine.hpp(run:851): Iteration 0/0, subinterval: 400798 - 626074
DEBUG:    memoryshard.hpp(load_edata:257): Compressed/full size: 0.34846 number of blocks: 23
INFO:     graphchi_engine.hpp(run:873): Start updates
INFO:     graphchi_engine.hpp(run:883): Finished updates
**\* Error in `/home/ubuntu/graphchi-prokopp/toolkits/collaborative_filtering/svd': free(): invalid size: 0x0000000044489d20 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x80a46)[0x7fe6e8906a46]
/home/ubuntu/graphchi-prokopp/toolkits/collaborative_filtering/svd[0x439d3b]
/home/ubuntu/graphchi-prokopp/toolkits/collaborative_filtering/svd[0x416899]
/home/ubuntu/graphchi-prokopp/toolkits/collaborative_filtering/svd[0x4193dd]
/home/ubuntu/graphchi-prokopp/toolkits/collaborative_filtering/svd[0x4051eb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fe6e88a7ea5]
/home/ubuntu/graphchi-prokopp/toolkits/collaborative_filtering/svd[0x406231]
======= Memory map: ========
00400000-0045d000 r-xp 00000000 08:01 1579028                            /home/ubuntu/graphchi-prokopp/toolkits/collaborative_filtering/svd
0065c000-0065d000 r--p 0005c000 08:01 1579028                            /home/ubuntu/graphchi-prokopp/toolkits/collaborative_filtering/svd
0065d000-0065e000 rw-p 0005d000 08:01 1579028                            /home/ubuntu/graphchi-prokopp/toolkits/collaborative_filtering/svd
0065e000-0065f000 rw-p 00000000 00:00 0
01006000-462d1000 rw-p 00000000 00:00 0                                  [heap]
7fdf7c000000-7fdf7ff14000 rw-p 00000000 00:00 0
7fdf7ff14000-7fdf80000000 ---p 00000000 00:00 0
7fdf80000000-7fdf83c01000 rw-p 00000000 00:00 0
[...]
7fe3b0000000-7fe3b4000000 rw-p 00000000 00:00 0
7fe3b4000000-7fe3b8000000 rw-p 00000000 00:00 0 Aborted (core dumped)

--- Next try ---

$ toolkits/collaborative_filtering/svd --training=/mnt/2/data.mm.mtx --nsv=50 --nv=55 mudget_mb 100000 nshards 1
[...]
DEBUG:    graphchi_engine.hpp(run:740): Engine being restarted, do not reinitialize.
INFO:     graphchi_engine.hpp(print_config:131): Engine configuration:
INFO:     graphchi_engine.hpp(print_config:132):  exec_threads = 32
INFO:     graphchi_engine.hpp(print_config:133):  load_threads = 4
INFO:     graphchi_engine.hpp(print_config:134):  membudget_mb = 100000
INFO:     graphchi_engine.hpp(print_config:135):  blocksize = 4194304
INFO:     graphchi_engine.hpp(print_config:136):  scheduler = 0
INFO:     graphchi_engine.hpp(run:759): Start iteration: 0
INFO:     graphchi_engine.hpp(run:838): 222.611s: Starting: 0 -- 14628414
INFO:     graphchi_engine.hpp(run:851): Iteration 0/0, subinterval: 0 - 14628414
DEBUG:    memoryshard.hpp(load_edata:257): Compressed/full size: 0.33842 number of blocks: 203
INFO:     graphchi_engine.hpp(run:873): Start updates
INFO:     graphchi_engine.hpp(exec_updates_inmemory_mode:481): In-memory mode: Iteration 0 starts. (273.507 secs)
**\* Error in `/home/ubuntu/graphchi-prokopp/toolkits/collaborative_filtering/svd': free(): invalid size: 0x00007fc4a7023670 ***
Segmentation fault (core dumped)

--- Next try ---

$ toolkits/collaborative_filtering/svd --training=/mnt/2/data.mm.mtx --nsv=5 --nv=5 mem
get_mb 100000 nshards 1
[...]
INFO:     graphchi_engine.hpp(exec_updates_inmemory_mode:481): In-memory mode: Iteration 0 starts. (188.425 secs)
INFO:     graphchi_engine.hpp(run:883): Finished updates
INFO:     graphchi_engine.hpp(run:723): GraphChi starting
INFO:     graphchi_engine.hpp(run:724): Licensed under the Apache License 2.0
INFO:     graphchi_engine.hpp(run:725): Copyright Aapo Kyrola et al., Carnegie Mellon University (2012)
DEBUG:    graphchi_engine.hpp(run:740): Engine being restarted, do not reinitialize.
INFO:     graphchi_engine.hpp(print_config:131): Engine configuration:
INFO:     graphchi_engine.hpp(print_config:132):  exec_threads = 32
INFO:     graphchi_engine.hpp(print_config:133):  load_threads = 4
INFO:     graphchi_engine.hpp(print_config:134):  membudget_mb = 100000
INFO:     graphchi_engine.hpp(print_config:135):  blocksize = 4194304
INFO:     graphchi_engine.hpp(print_config:136):  scheduler = 0
INFO:     graphchi_engine.hpp(run:759): Start iteration: 0
INFO:     graphchi_engine.hpp(run:838): 194.59s: Starting: 0 -- 14628414
INFO:     graphchi_engine.hpp(run:851): Iteration 0/0, subinterval: 0 - 14628414
DEBUG:    memoryshard.hpp(load_edata:257): Compressed/full size: 0.33842 number of blocks: 203
INFO:     graphchi_engine.hpp(run:873): Start updates
INFO:     graphchi_engine.hpp(exec_updates_inmemory_mode:481): In-memory mode: Iteration 0 starts. (249.173 secs)
**\* Error in `...../toolkits/collaborative_filtering/svd': munmap_chunk(): invalid pointer: 0x00007fb6c1976070 ***
Segmentation fault (core dumped)

**Comment by Pengeace** [comment]
I also meet this problem。。。
